# RabbitMQ Cluster Operator
#
# Copyright 2020 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Mozilla Public license, Version 2.0 (the "License").  You may not use this product except in compliance with the Mozilla Public License.
#
# This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - bindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - exchanges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - exchanges/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - exchanges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - federations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - federations/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - federations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - permissions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - policies/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - policies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - queues/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - queues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters/status
  verbs:
  - get
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - schemareplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - schemareplications/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - schemareplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - shovels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - shovels/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - shovels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreams/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - superstreams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - topicpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - topicpermissions/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - topicpermissions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts/finalizers
  verbs:
  - update
- apiGroups:
  - rabbitmq.com
  resources:
  - vhosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - get
  - list
  - update
  - watch
